[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "fade"]
set = true

[templates.ignis]
input_path = './templates/colors.scss'
output_path = '/home/yanping/dotfiles/ignis/colors.scss'

[templates.hypr]
input_path = './templates/colors.conf'
output_path = '/home/yanping/.config/hypr/colors.conf'

[templates.hyprlock]
input_path = './templates/hyprlock.conf'
output_path = '/home/yanping/.config/hypr/hyprlock.conf'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '/home/yanping/dotfiles/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '/home/yanping/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '/home/yanping/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/qt-colors.conf'
output_path = '/home/yanping/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qt-colors.conf'
output_path = '/home/yanping/.config/qt6ct/colors/matugen.conf'

[templates.vscode] # hyprluna
input_path = "~/.config/matugen/templates/hyprlunavsc.json"
output_path = "/home/yanping/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"

# [templates.waybar]
# input_path = '/home/yanping/dotfiles/matugen/templates/colors.css'
# output_path = '/home/yanping/dotfiles/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.starship]
input_path = '/home/yanping/dotfiles/matugen/templates/starship.toml'
output_path = '/home/yanping/dotfiles/starship/starship.toml'

[templates.tmux]
input_path = './templates/tmux-theme.conf'
output_path = '/home/yanping/dotfiles/tmux/modules/appearance.conf'
post_hook = 'tmux source-file ~/dotfiles/tmux/tmux.conf 2>/dev/null || true'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '/home/yanping/dotfiles/btop/themes/matugen.theme'

[templates.rofi]
input_path = '/home/yanping/dotfiles/matugen/templates/rofi.rasi'
output_path = '/home/yanping/dotfiles/rofi/colors.rasi'
